### ISSUE TITLE
Customer can't cancel a reservation, the owner can't delete a property.

### ISSUE THREAD

**Issue by Xinyue-Ma** [Jray810/CS4400_Team77#66]
<img width="1217" alt="Screen Shot 2021-12-15 at 8 53 54 PM" src="https://user-images.githubusercontent.com/55669183/146293605-b0c15c7d-2784-42ee-adc7-d973e5baa56b.png">
Customer pages -> my reservation -> my future reservations -> cancel -> cancel reservation

The reservation won't be canceled. Null values are passed to MySQL procedure as follows.
```
2021-12-15 20:54:40,284 INFO sqlalchemy.engine.Engine CALL cancel_property_reservation('', '', '', '2021-12-15')
```
There is a reserve button here. Click the reserve button. It leads to inputting the # of people and redirecting to the make a reservation page.

---

Here is also a reserve button above in the details pop up window. It won't work after clicking.

<img width="868" alt="Screen Shot 2021-12-15 at 9 00 07 PM" src="https://user-images.githubusercontent.com/55669183/146294160-0620a2b6-7610-484c-af14-c538f53d8177.png">

---

Owners pages -> my properties -> details -> remove property
The remove property is not working. The null values are passed to remove_property procedure.
```
CALL remove_property('', '', '2021-12-15')
```

**Comment by neilgbarry** [comment]
This should be fixed, please test
